/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ittimfn.servlet;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@WebServlet("/myservlet")
public class MyServlet extends HttpServlet {

    private Logger logger = LogManager.getLogger(MyServlet.class);

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException {
        logger.info("Hello Log4j2!!");
        res.setContentType("text/html; charset=utf-8");
            try (PrintWriter out = res.getWriter()) {
                out.println("<html><body>");
                out.println("サーブレット: Hello Servlet World!<br>");
                out.println(getServletContext().getServerInfo());
                out.println("</body></html>");
        }
    }
}