FROM tomcat:9.0.109-jdk8-temurin-noble

RUN rm -f $CATALINA_HOME/lib/commons-daemon.jar \ 
    rm -f $CATALINA_HOME/lib/catalina-ant.jar \ 
    rm -f $CATALINA_HOME/lib/catalina-ssi.jar \ 
    rm -f $CATALINA_HOME/lib/catalina-storeconfig.jar \ 
    rm -f $CATALINA_HOME/lib/catalina-tribes.jar \ 
#    rm -f $CATALINA_HOME/lib/ecj-4.20.jar \ 
#    rm -f $CATALINA_HOME/lib/el-api.jar \ 
#    rm -f $CATALINA_HOME/lib/jasper-el.jar \ 
#    rm -f $CATALINA_HOME/lib/jasper.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-coyote-ffm.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-dbcp.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-cs.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-de.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-es.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-fr.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-ja.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-ko.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-pt-BR.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-ru.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-i18n-zh-CN.jar \ 
    rm -f $CATALINA_HOME/lib/tomcat-websocket.jar \ 
    rm -f $CATALINA_HOME/lib/websocket-api.jar
RUN ls $CATALINA_HOME/bin
    
